namespace: hello-api-dev

resources:
  - ../../base

images:
  - name: go-app
    newName: docker.io/vatthanachaiw/go-app
    newTag: latest
    
patches:
  - path: patch-deployment.yaml
  - path: patch-configmap.yaml
