apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: go-app
        resources:
          limits:
            memory: "512Mi"
            cpu: "1"