namespace: go-app-dev

resources:
  - ../../base

images:
  - name: go-app
    newName: docker.io/vatthanachaiw/go-app
    newTag: "gcr.io/$GITHUB_SHA"
    
patches:
  - path: patch-deployment.yaml
  - path: patch-configmap.yaml
