name: Deploy to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  CLUSTER_NAME: hello-gke-cluster-development
  REGION: asia-southeast1

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: Development

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - name: Install GKE Auth Plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin
           export USE_GKE_GCLOUD_AUTH_PLUGIN=True
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
      
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/go-app:${{ github.sha }} .
      
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/go-app:${{ github.sha }}
      
      - name: Get GKE Credentials
        run: gcloud container clusters get-credentials "$CLUSTER_NAME" --region "$REGION" --project "$PROJECT_ID"

#      - name: List Files and Directories
#        run: find "$(pwd)" -type d
        
      - name: Update Deployment
        run: |
          cd $GITHUB_WORKSPACE/k8s/overlays/prod
          kustomize edit set image docker.io/vatthanachaiw/go-app=docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/go-app:${{ github.sha }}
      
      - name: Display Kustomization YAML
        run: |
          cat $GITHUB_WORKSPACE/k8s/overlays/prod/kustomization.yaml
      
      - name: Deploy to GKE
        run: |
          kubectl apply -k $GITHUB_WORKSPACE/k8s/overlays/prod 
          kubectl rollout status deployment/go-app
